[package]
name = "kvs"
version = "0.1.0"
authors = ["xincheng <2240131203@qq.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = { version = "3.2.12", features = ["cargo", "env"] }


[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"


